Add asdf Ruby & Elixir versions to the prompt

diff --git a/zsh/prompts/prompt_pure_setup b/zsh/prompts/prompt_pure_setup
--- a/zsh/prompts/prompt_pure_setup
+++ b/zsh/prompts/prompt_pure_setup
@@ -104,6 +104,21 @@ prompt_pure_check_ruby_version(){
 	# reset ruby version
 	prompt_pure_ruby_version=
 
+  if type asdf >/dev/null
+  then
+    local ruby_version
+    asdf_rb_version="$(asdf current ruby 2>&1)"
+
+    # exit if the command failed
+    (( !$? )) || return
+
+    if ( echo "$asdf_rb_version" | grep -qv "set by $HOME/.tool-versions" ); then
+      ruby_version="$(echo ${asdf_rb_version} | cut -d' ' -f1)"
+      prompt_pure_ruby_version=" ‹${ruby_version}›"
+      return
+    fi
+  fi
+
   if type rbenv >/dev/null
   then
     local ruby_version
@@ -118,6 +133,27 @@ prompt_pure_check_ruby_version(){
     [[ -n $ruby_version ]] &&
     [[ "$ruby_version" != "$ruby_global_version" ]] &&
     prompt_pure_ruby_version=" ‹${ruby_version}›"
+    return
+  fi
+}
+
+prompt_pure_check_elixir_version(){
+	# reset elixir version
+	prompt_pure_elixir_version=
+
+  if type asdf >/dev/null
+  then
+    local elixir_version
+    asdf_elixir_version="$(asdf current elixir 2>&1)"
+
+    # exit if the command failed
+    (( !$? )) || return
+
+    if ( echo "$asdf_elixir_version" | grep -qv "set by $HOME/.tool-versions" ); then
+      elixir_version="$(echo ${asdf_elixir_version} | cut -d' ' -f1)"
+      prompt_pure_elixir_version=" ‹${elixir_version}›"
+      return
+    fi
   fi
 }
 
@@ -157,6 +193,8 @@ prompt_pure_preprompt_render() {
 	preprompt+="%F{blue}%~%f"
   # show the Ruby version if not the rbenv global one
   preprompt+="%F{198}${prompt_pure_ruby_version}%f"
+  # show the Elixir version if not the rbenv global one
+  preprompt+="%F{198}${prompt_pure_elixir_version}%f"
 	# git info
 	preprompt+="%F{$git_color}${vcs_info_msg_0_}${prompt_pure_git_dirty}%f"
 	# git pull/push arrows
@@ -265,9 +303,6 @@ prompt_pure_async_git_fetch() {
 	GIT_TERMINAL_PROMPT=0 command git -c gc.auto=0 fetch
 }
 
-prompt_pure_async_ruby_version(){
-}
-
 prompt_pure_async_tasks() {
 	# initialize async worker
 	((!${prompt_pure_async_init:-0})) && {
@@ -294,6 +329,7 @@ prompt_pure_async_tasks() {
 
 
   async_job "prompt_pure" prompt_pure_async_ruby_version "${working_tree}"
+  async_job "prompt_pure" prompt_pure_async_elixir_version "${working_tree}"
 
 	# only perform tasks inside git working tree
 	[[ -n $working_tree ]] || return
@@ -336,6 +372,11 @@ prompt_pure_async_callback() {
 
     prompt_pure_async_ruby_version)
       prompt_pure_check_ruby_version
+			prompt_pure_preprompt_render
+      ;;
+
+    prompt_pure_async_elixir_version)
+      prompt_pure_check_elixir_version
 			prompt_pure_preprompt_render
       ;;
 	esac
