Make ASDF version checks async

diff --git a/zsh/functions/prompt_parts b/zsh/functions/prompt_parts
--- a/zsh/functions/prompt_parts
+++ b/zsh/functions/prompt_parts
@@ -61,16 +61,13 @@ rprompt_setup(){
 }
 
 asdf_version(){
-  if type asdf > /dev/null 2>&1; then
-    local app_version
-    app_version="$(asdf current "$1" 2>&1)"
+  local app_version="$(asdf current "$1" 2>&1)"
 
-    # exit if the command failed
-    (( !$? )) || return 1
+  # exit if the command failed
+  (( !$? )) || return 1
 
-    if ( echo "$app_version" | grep -qv "set by $HOME/.tool-versions" ); then
-      echo -n "$(echo ${app_version} | cut -d' ' -f1)"
-    fi
+  if ( echo "$app_version" | grep -qv "set by $HOME/.tool-versions" ); then
+    echo -n "$(echo ${app_version} | cut -d' ' -f1)"
   fi
 }
 
@@ -86,17 +83,19 @@ prompt_version(){
 prompt_tool_versions(){
   tools=""
 
-  ruby="$(prompt_version 'ruby')"
-  [[ -z "$ruby" ]] || tools+="%F{198}$(prompt_version 'ruby')%f"
+  if type asdf > /dev/null 2>&1; then
+    ruby="$(prompt_version 'ruby')"
+    [[ -z "$ruby" ]] || tools+="%F{198}$(prompt_version 'ruby')%f"
 
-  elixir="$(prompt_version 'elixir')"
-  [[ -z "$elixir" ]] || tools+="%F{99}$(prompt_version 'elixir')%f"
+    elixir="$(prompt_version 'elixir')"
+    [[ -z "$elixir" ]] || tools+="%F{99}$(prompt_version 'elixir')%f"
 
-  postgres="$(prompt_version 'postgres')"
-  [[ -z "$postgres" ]] || tools+="%F{32}$(prompt_version 'postgres')%f"
+    postgres="$(prompt_version 'postgres')"
+    [[ -z "$postgres" ]] || tools+="%F{32}$(prompt_version 'postgres')%f"
 
-  nodejs="$(prompt_version 'nodejs')"
-  [[ -z "$nodejs" ]] || tools+="%F{148}$(prompt_version 'nodejs')%f"
+    nodejs="$(prompt_version 'nodejs')"
+    [[ -z "$nodejs" ]] || tools+="%F{148}$(prompt_version 'nodejs')%f"
+  fi
 
-  echo -n "$tools"
+  echo "$tools"
 }
